<div id="es-1" name="es-1" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
	Espere un momento, por favor...
	<div class="progress">
		<div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
			<span class="sr-only">100% Completo</span>
		</div>
	</div>
</div>

<form name="frm-1" id="frm-1" method="post" action="/usuario/guardarpermisos">
	
	<div class="form-group">
		<label class="control-label">
			Nombre: <?php echo($this->nombre); ?>
		</label>
	</div>
	
	<div class="form-group">
		
		<ul id="tabs" name="tabs" class="nav nav-tabs">
			<li class="active">
				<a data-toggle="tab" href="#seccion-1">
					Cat&aacute;logos
				</a>
			</li>
			<li>
				<a data-toggle="tab" href="#seccion-2">
					Impuestos
				</a>
			</li>
		</ul>
		
		<div class="tab-content">
			
			<!-- Sección 1 -->
			<div id="seccion-1" class="tab-pane fade in active">
				<table class="table table-striped table-bordered table-hover table-condensed">
					<thead>
						<th>M&oacute;dulo</th>
						<th width="100">Ver</th>
						<th width="100">Agregar</th>
						<th width="100">Editar</th>
						<th width="100">Eliminar</th>
						<th width="100">Documentos</th>
						<th width="100">Permisos</th>
					</thead>
					<tbody>
						<tr>
							<td>Bit&aacute;cora</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_BITACORA" <?php echo (in_array("VER_BITACORA", $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center">&nbsp;</td>
							<td align="center">&nbsp;</td>
							<td align="center">&nbsp;</td>
							<td align="center">&nbsp;</td>
						</tr>
						<tr>
							<td>Usuario</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_USUARIO"      <?php echo (in_array("VER_USUARIO",      $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_USUARIO"  <?php echo (in_array("AGREGAR_USUARIO",  $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_USUARIO"   <?php echo (in_array("EDITAR_USUARIO",   $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_USUARIO" <?php echo (in_array("ELIMINAR_USUARIO", $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="PERMISOS_USUARIO" <?php echo (in_array("PERMISOS_USUARIO", $this->permisos)) ? "checked" : "" ?> /></td>
						</tr>
						<tr>
							<td>Empresa</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_EMPRESA"      <?php echo (in_array("VER_EMPRESA",      $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_EMPRESA"  <?php echo (in_array("AGREGAR_EMPRESA",  $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_EMPRESA"   <?php echo (in_array("EDITAR_EMPRESA",   $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_EMPRESA" <?php echo (in_array("ELIMINAR_EMPRESA", $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"></td>
							<td align="center"></td>
						</tr>
						<tr>
							<td>Ejercicios</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_EJERCICIO"      <?php echo (in_array("VER_EJERCICIO",      $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_EJERCICIO"  <?php echo (in_array("AGREGAR_EJERCICIO",  $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_EJERCICIO"   <?php echo (in_array("EDITAR_EJERCICIO",   $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_EJERCICIO" <?php echo (in_array("ELIMINAR_EJERCICIO", $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"></td>
							<td align="center"></td>
						</tr>
						
						<tr>
							<td>Autorización</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_AUTORIZACION" <?php echo (in_array("VER_AUTORIZACION", $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"></td>
							<td align="center"></td>
							<td align="center"></td>
							<td align="center"></td>
							<td align="center"></td>
						</tr>
					</tbody>
				</table>
			</div>
			
			<!-- Sección 2 -->
			<div id="seccion-2" class="tab-pane fade">
				<table class="table table-striped table-bordered table-hover table-condensed">
					<thead>
						<th>M&oacute;dulo</th>
						<th width="100">Ver</th>
						<th width="100">Agregar</th>
						<th width="100">Editar</th>
						<th width="100">Eliminar</th>
						<th width="100">Documentos</th>
						<th width="100">Permisos</th>
					</thead>
					<tbody>
						<tr>
							<td>Subsidio al empleo</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_SUBSIDIO" <?php echo (in_array("VER_SUBSIDIO", $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center">&nbsp;</td>
							<td align="center">&nbsp;</td>
							<td align="center">&nbsp;</td>
							<td align="center">&nbsp;</td>
						</tr>
						
						<tr>
							<td>Compensaciones</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_COMPENSACIONES"      <?php echo (in_array("VER_COMPENSACIONES",      $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_COMPENSACIONES"  <?php echo (in_array("AGREGAR_COMPENSACIONES",  $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_COMPENSACIONES"   <?php echo (in_array("EDITAR_COMPENSACIONES",   $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_COMPENSACIONES" <?php echo (in_array("ELIMINAR_COMPENSACIONES", $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"></td>
							<td align="center"></td>
						</tr>
						
						<tr>
							<td>Coeficiente de utilidad</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_COEFICIENTE"      <?php echo (in_array("VER_COEFICIENTE", $this->permisos))      ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_COEFICIENTE"  <?php echo (in_array("AGREGAR_COEFICIENTE",  $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_COEFICIENTE"   <?php echo (in_array("EDITAR_COEFICIENTE",   $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_COEFICIENTE" <?php echo (in_array("ELIMINAR_COEFICIENTE", $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"></td>
							<td align="center"></td>
						</tr>
						
						<tr>
							<td>Coeficiente de acreditamiento</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_COEFICIENTE_ACRE"      <?php echo (in_array("VER_COEFICIENTE_ACRE",      $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_COEFICIENTE_ACRE"  <?php echo (in_array("AGREGAR_COEFICIENTE_ACRE",  $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_COEFICIENTE_ACRE"   <?php echo (in_array("EDITAR_COEFICIENTE_ACRE",   $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_COEFICIENTE_ACRE" <?php echo (in_array("ELIMINAR_COEFICIENTE_ACRE", $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"></td>
							<td align="center"></td>
						</tr>
						
						<tr>
							<td>Pago provisional PM</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_PAGOPM" <?php echo (in_array("VER_PAGOPM", $this->permisos)) ? "checked" : "" ?> /></td>
							<td align="center"></td>
							<td align="center"></td>
							<td align="center"></td>
							<td align="center"></td>
							<td align="center"></td>
						</tr>
					</tbody>
				</table>
				
				<div class="col-xs-12" style="overflow: hidden;">
					<div class="row multiple-double-select m-b-2">
						<h4 class="m-b-2">Empresas</h4>
						
						<div class="row">
							<div class="col-xs-5">
								<h5>Empresas disponibles</h5>
								<input type="text" name="available" id="available" class="form-control input-sm" placeholder="Buscar" />
								<button type="button" id="search-available" class="search-button btn btn-rojo-1 m-l-2" onclick="filtrarEmpresas(this.id);">Buscar</button>
								
								<div class="m-t-2 multiselect">
									<div class="col-xs-12 center loading">
										 <img src="../public/imagenes/loader.gif" alt="loading" height="42" width="42"> 
									</div>
									
									<ul id="disponibles">
										<?php 
										foreach($this->empresas AS $empresa) { 
											if ( $empresa['user'] == null ) { ?>
												<li><div><?php echo $empresa['nombre']; ?></div><input type="checkbox" name="empresas[]" value="<?php echo $empresa['id']; ?>"></li>
									<?php   }
										} ?>
									</ul>
								</div>
							</div>
							
							<div class="col-xs-2 select-buttons">
								<button type="button" class="btn btn-rojo-1 m-b-2" onclick="agregarEmpresa();"><i class="fa fa-angle-double-right fa-2x"></i></button>
								<button type="button" class="btn btn-rojo-1 " onclick="quitarEmpresa();"><i class="fa fa-angle-double-left fa-2x"></i></button>
							</div>
							
							<div class="col-xs-5">
								<h5>Empresas asignadas</h5>
								<input type="text" name="assigment" id="assigment" class="form-control input-sm" placeholder="Buscar" />
								<button type="button" id="search-assigment" class="search-button btn btn-rojo-1 m-l-2" onclick="filtrarEmpresas(this.id);">Buscar</button>
								
								<div class="m-t-2 multiselect">
									<div class="col-xs-12 center loading">
										 <img src="../public/imagenes/loader.gif" alt="loading" height="42" width="42"> 
									</div>
									
									<ul id="seleccionados">
										<?php 
										foreach($this->empresas AS $empresa) { 
											if ( $empresa['user'] != null ) { ?>
												<li><div><?php echo $empresa['nombre']; ?></div><input type="checkbox" name="empresas[]" value="<?php echo $empresa['id']; ?>"></li>
									<?php   }
										} ?>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<input type="hidden" name="id" id="id" value="<?php echo $this->registro->id ?>" />
	<div class="text-right"> 
		<button class="btn btn-rojo-1" onclick="guardarPermisos();" type="button" >
			<i class="fa fa-check-circle"></i>
			Aceptar
		</button>
		<button class="btn btn-rojo-1" onclick="cancelar();" type="button" >
			<i class="fa fa-times-circle"></i> 
			Cancelar
		</button>
	</div>
	
	<br/><br/><br/>
</form>

<?php
/*

<!--
<tr>
	<td>Tipos de impuestos</td>
	<td align="center"><input type="checkbox" name="permisos[]" value="VER_TIPO_IMPUESTOS"      <?php echo (in_array("VER_TIPO_IMPUESTOS",      $this->permisos)) ? "checked" : "" ?> /></td>
	<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_TIPO_IMPUESTOS"  <?php echo (in_array("AGREGAR_TIPO_IMPUESTOS",  $this->permisos)) ? "checked" : "" ?> /></td>
	<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_TIPO_IMPUESTOS"   <?php echo (in_array("EDITAR_TIPO_IMPUESTOS",   $this->permisos)) ? "checked" : "" ?> /></td>
	<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_TIPO_IMPUESTOS" <?php echo (in_array("ELIMINAR_TIPO_IMPUESTOS", $this->permisos)) ? "checked" : "" ?> /></td>
	<td align="center"></td>
	<td align="center"></td>
</tr>
<tr>
	<td>Tipos de empresas</td>
	<td align="center"><input type="checkbox" name="permisos[]" value="VER_TIPO_EMPRESAS"      <?php echo (in_array("VER_TIPO_EMPRESAS",      $this->permisos)) ? "checked" : ""?> /></td>
	<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_TIPO_EMPRESAS"  <?php echo (in_array("AGREGAR_TIPO_EMPRESAS",  $this->permisos)) ? "checked" : ""?> /></td>
	<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_TIPO_EMPRESAS"   <?php echo (in_array("EDITAR_TIPO_EMPRESAS",   $this->permisos)) ? "checked" : ""?> /></td>
	<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_TIPO_EMPRESAS" <?php echo (in_array("ELIMINAR_TIPO_EMPRESAS", $this->permisos)) ? "checked" : ""?> /></td>
	<td align="center"></td>
	<td align="center"></td>
</tr>
-->

<!--
<tr>
	<td>Configuración</td>
	<td align="center"><input type="checkbox" name="permisos[]" value="VER_CONFIGURACION"      <?php echo (in_array("VER_CONFIGURACION",      $this->permisos)) ? "checked" : "" ?> /></td>
	<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_CONFIGURACION"  <?php echo (in_array("AGREGAR_CONFIGURACION",  $this->permisos)) ? "checked" : "" ?> /></td>
	<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_CONFIGURACION"   <?php echo (in_array("EDITAR_CONFIGURACION",   $this->permisos)) ? "checked" : "" ?> /></td>
	<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_CONFIGURACION" <?php echo (in_array("ELIMINAR_CONFIGURACION", $this->permisos)) ? "checked" : "" ?> /></td>
	<td align="center"></td>
	<td align="center"></td>
</tr>
-->

<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_AUTORIZACION"  <?php echo (in_array("AGREGAR_AUTORIZACION",  $this->permisos)) ? "checked" : "" ?> /></td>
<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_AUTORIZACION"   <?php echo (in_array("EDITAR_AUTORIZACION",   $this->permisos)) ? "checked" : "" ?> /></td>
<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_AUTORIZACION" <?php echo (in_array("ELIMINAR_AUTORIZACION", $this->permisos)) ? "checked" : "" ?> /></td>

*/
?>