<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <!-- Quitar los responsivo -->
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
        <meta name="description" content="Toma Nota">
        <title>Sistema::Administrativo</title>
        <link rel="stylesheet" type="text/css" href="/recursos/jquery_ui_1_10_4_custom/css/custom-theme/jquery-ui-1.10.4.custom.min.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/bootstrap_3_2_0/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/flexigrid_1_1/css/flexigrid.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/normalize_2_1_3/normalize.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/font_awesome_4_1_0/css/font-awesome.min.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/jquery_multiselect_1_13/jquery.multiselect.css" />
        <link rel="stylesheet" type="text/css" href="/css/default.css" />
        <link rel="stylesheet" type="text/css" href="/css/personalizado.css" />
        <?php echo $this->headLink(); ?>

        <link rel="apple-touch-icon" sizes="180x180" href="/imagenes/apple-touch-icon.png">
        <link rel="icon" type="image/png" href="/imagenes/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="/imagenes/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="/imagenes/manifest.json">
        <link rel="mask-icon" href="/imagenes/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="shortcut icon" href="/imagenes/favicon.ico">
        <meta name="msapplication-TileColor" content="#e21f19">
        <meta name="msapplication-TileImage" content="/imagenes/mstile-144x144.png">
        <meta name="msapplication-config" content="/imagenes/browserconfig.xml">
        <meta name="theme-color" content="#ffffff">

    </head>
    <body>
        <section role="main">
            <div class="container">
                <?php echo $this->layout()->content; ?>
            </div>                                
        </section>

        <input type="hidden" name="_peticion" id="_peticion" value="<?php echo $this->peticion; ?>" />
        <input type="hidden" name="_modulo" id="_modulo" value="<?php echo $this->modulo; ?>" />
        <input type="hidden" name="_controlador" id="_controlador" value="<?php echo $this->controlador; ?>" />
        <input type="hidden" name="_accion" id="_accion" value="<?php echo $this->accion; ?>" />

        <div id="_dialogo-1" class="display-none"></div>
        <div id="_dialogo-2" class="display-none"></div>
        <div id="_dialogo-pausa-notificacion" class="display-none"></div>
        <div id="_mensaje-1" class="display-none"></div>
        <div id="_mensaje-2" class="display-none"></div>
        
        <!-- La carga de los scripts debe hacerse al final -->
        <script src="/recursos/jquery_2_0_3/jquery-2.0.3.min.js"></script>
        <script src="/recursos/jquery_ui_1_10_4_custom/js/jquery-ui-1.10.4.custom.min.js"></script>
        <script src="/recursos/bootstrap_3_2_0/js/bootstrap.min.js"></script>
        <script src="/recursos/jquery_form_3_18/ajaxforms.js"></script>
        <script src="/recursos/jquery_validation_1_13_0/dist/jquery.validate.min.js"></script>    
        <script src="/recursos/jquery_validation_1_13_0/dist/localization/messages_es.min.js"></script>    
        <script src="/recursos/flexigrid_1_1/js/flexigrid.js"></script>
        <script src="/recursos/jquery_multiselect_1_13/jquery.multiselect.min.js"></script>
        <script src="/js/default/comun.js"></script>
        <?php echo $this->headScript(); ?>               
    </body>
</html>