<div id="es-2" name="es-2" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
	Espere un momento, por favor...
	<div class="progress">
		<div class="progress-bar progress-bar-success progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
			<span class="sr-only">100% Completo</span>
		</div>
	</div>
</div>
<form id="frm-2" name="frm-2" method="post" action="/backend/ingreso/recuperar" role="form">
	<div class="alert alert-info" role="alert">
		Ingrese la direcci&oacute;n de correo electr&oacute;nico con la que se registr&oacute;, el sistema validar&aacute; y enviar&aacute; los datos de acceso si es que son encontrados.
	</div>
	<div class="form-group">
		<label for="correo_electronico" class="sr-only">*Correo electr&oacute;nico:</label>
		<input type="email" id="correo_electronico" name="correo_electronico" class="form-control required email" value="" placeholder="Correo electr&oacute;nico">
	</div>
</form>