<form id="frm-check" name="frm-check" class="form-horizontal" method="post" action="/autorizacion/guardar-autorizacion" role="form">
	<div class="card">
		<div class="card-block">
			<table style="width: 100%;">
				<thead>
					<th class="text-center col-xs-3">Impuesto</th>
					<th class="text-center col-xs-3">Tipo</th>
					<th class="text-center col-xs-2">Remanente</th>
					<th class="text-center col-xs-2">Monto total</th>
					<th class="text-center col-xs-2">Monto aplicado</th>
				</thead>
				<tbody>
					<tr>
						<td class="text-center col-xs-3"><?php echo utf8_encode($this->impuesto->nombre); ?></td>
						<td class="text-center col-xs-3"><?php echo $this->tipo; ?></td>
						<td class="text-center col-xs-2">$<?php echo number_format($this->remanente, 2); ?></td>
						<td class="text-center col-xs-2">$<?php echo $this->monto; ?></td>
						<td class="text-center col-xs-2">
							<input name="monto" id="monto" type="text" class="form-control input-sm required" value="<?php echo $this->monto; ?>">
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</form>