<div class="panel panel-default" style="margin: 5px 0;">
	<div class="pnl-heading-rojo-1 clearfix">
		<h3 class="panel-title pull-left">Ejercicios</h3>
	</div>
	
	<div class="panel-body">
		<div class="row margin-bottom-3">
			<form id="frmFiltroEjercicio" name="frmFiltroEjercicio">
				
				<div class="col-xs-2">
					<label for="fnombre" class="sr-only">Nombre</label>
					<input type="text" name="nombre" id="fnombre" class="form-control input-sm" value="" placeholder="Nombre de ejercicio"/>
				</div>
				<div class="col-xs-2">
					<label for="fstatus" class="sr-only">Estatus</label>
					<select id="fstatus" name="fstatus" class="form-control input-sm">
						<option value="" >- Todos los estatus -</option>
						<option value="1" selected>Activo</option>
						<option value="0">Inactivo</option>
					</select>
				</div>
				
				<div class="col-xs-8 text-right">
					<a class="btn btn-sm btn-default" type="button" onclick="filtrar('frmFiltroEjercicio','/ejercicio/grid','/ejercicio/imprimir','/ejercicio/exportar');">
						<i class="fa fa-search"></i>&nbsp;Filtrar
					</a>
					<a class="btn btn-sm btn-default" type="button" onclick="limpiar('frmFiltroEjercicio','/ejercicio/grid');">
						<i class="fa fa-eraser"></i>&nbsp;Limpiar
					</a>
					<!--
					<a id="btnImprimir" target="_blank" href="/ejercicio/imprimir" class="btn btn-sm btn-default" >
						<i class="fa fa-search"></i>&nbsp;Imprimir
					</a>
					<a id="btnExportar" target="_blank" href="/ejercicio/exportar" class="btn btn-sm btn-default"  >
						<i class="fa fa-eraser"></i>&nbsp;Exportar
					</a>-->
				</div>
			</form>
		</div>
	</div>
	
	<form id="frmEjercicio" name="frmEjercicio" method="post" action="/ejercicio/guardar" role="form">
		<div class="panel-body">
			<div class="row margin-bottom-3">
				<div class="col-xs-7 sinMargin">
					<div class="pnl-heading-rojo-1 clearfix"><h3 class="panel-title text-center">Ejercicios</h3></div>
					<div id="flexigrid"></div>
				</div>
				
				<div class="col-xs-5 sinPaddingLeft">
					<div class="panel panel-default" >
						<div class="pnl-heading-rojo-1 clearfix">
							<h3 class="panel-title pull-left">Alta / Edición de Ejercicio</h3>
						</div>
						<div class="panel-body">
							<div class="row margin-bottom-3">
								<div class="col-xs-12 form-group"> 
									<label for="nombre" class="col-xs-4 control-label" style="padding: 0px;"><span class="naranja">*</span>Nombre:</label>
									<div class="col-xs-8 sinPaddingRight">
										<input type="text" id="nombre" name="nombre" class="form-control input-sm required" value=""  maxlength="100" placeholder="Nombre" />
									</div>
								</div>
								<div class="col-xs-12 form-group"> 
									<label for="status" class="col-xs-4 control-label" style="padding: 0px;"><span class="naranja">*</span>Estatus:</label>
									<div class="col-xs-8 sinPaddingRight">
										<select id="status" name="status" class="form-control required" <?php echo($this->puedeAgregar?"":'disabled="disabled"'); ?>">
											<option value="1">Activo</option>
											<option value="0">Inactivo</option>
										</select>
									</div>
								 </div>
							</div>
							
							<div class="row sinMargin text-center">
								<div class="col-xs-4 text-center mt40px">
									<button type="button" onclick="guardar('frmEjercicio','/ejercicio/grid','/ejercicio/imprimir','/ejercicio/exportar');" class="col-xs-12 btn btn-success marginLat5p <?php echo(($this->puedeAgregar)?"":"hide"); ?>">
										<i class="fa fa-floppy-o"></i>&nbsp;Guardar
									</button>
								</div>
								<div class="col-xs-4 text-center mt40px"> 
									<button type="button" onclick="limpiarfrmEjercicio();" class="col-xs-12 btn btn-primary marginLat5p <?php echo(($this->puedeAgregar)?'':'hide'); ?>">
										<i class="fa fa-eraser"></i>&nbsp;Limpiar
									</button>
								</div>
								<div class="col-xs-4 text-center mt40px">
									<a onclick="eliminar('','1');" id="eliminar" class="col-xs-12 btn btn-danger  marginLat5p <?php echo(($this->puedeEliminar)?'':'hide'); ?>">
										<i class="fa fa-times"></i>&nbsp;Eliminar
									</a>
								</div>
								<input type="hidden" name="id" id="id" value="" />
							</div>
						</div>
					</div>
				</div> 
			</div>
		</div>
	</form>
</div>