<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <!-- Quitar los responsivo -->
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
        <meta name="description" content="Avansys">
        <title>Heza</title>
        <link rel="stylesheet" type="text/css" href="/recursos/jquery_ui_1_11_4/jquery-ui.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/bootstrap/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/flexigrid/flexigrid.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/normalize/normalize_3_0_3.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/font-awesome-4-6-3/css/font-awesome.css" />
        <link rel="stylesheet" type="text/css" href="/css/comun.css" />
        <link rel="stylesheet" type="text/css" href="/css/backend.css" />

        <?php echo $this->headLink(); ?>
        <link rel="apple-touch-icon" sizes="180x180" href="/imagenes/apple-touch-icon.png">
        <link rel="icon" type="image/png" href="/imagenes/faviconheza-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="/imagenes/faviconheza-16x16.png" sizes="16x16">
        <link rel="manifest" href="/imagenes/manifest.json">
        <link rel="mask-icon" href="/imagenes/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="shortcut icon" href="/imagenes/faviconheza.ico">
        <meta name="msapplication-TileColor" content="#e21f19">
        <meta name="msapplication-TileImage" content="/imagenes/mstile-144x144.png">
        <meta name="msapplication-config" content="/imagenes/browserconfig.xml">
        <meta name="theme-color" content="#ffffff">
    
    </head>
    <body>

        <header class="banner">
            <div class="encabezado">
                <figure class="pull-left">
                    <img src="/imagenes/logo-heza.png" class="logo" alt="Onappafa" title="Onappafa" />
                </figure>
                <div class="row">
                    <center><h1 class="mt40px bold f24px">Sistema Administrativo</h1></center>
                </div>
            </div>
        </header>

        <div class="container">
            <div class="row">
                <div class="col-xs-offset-3 col-xs-6">
                    <div class="panel panel-default" style="margin-top: 80px;">
                        <div class="pnl-heading-rojo-1">
                            <h3 class="panel-title"><i class="fa fa-user"></i>&nbsp; Ingreso</h3>
                        </div>
                        
                        <div class="panel-body">
                            <div id="es-1" name="es-1" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
                                Espere un momento, por favor...
                                <div class="progress">
                                    <div class="progress-bar progress-bar-success progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                        <span class="sr-only">100% Completo</span>
                            </div>
                                </div>
                            </div>
                        
                            <form id="frm-1" name="frm-1" method="post" action="/ingreso/ingresar" role="form">
                                <div class="form-group">
                                    <!--<label for="correo_electronico" class="sr-only">*N&uacute;mero de empleado:</label>-->
                            <!--<input type="text" id="numero" name="numero" class="form-control required number" value="" placeholder="N&uacute;mero de empleado">-->
                                                    
                            <input type="email" id="correo_electronico" name="correo_electronico" class="form-control required email" value="" placeholder="Correo electr&oacute;nico">
                                </div>
                                
                                <div class="form-group">
                                    <label for="contrasena" class="sr-only">*Contrase&ntilde;a:</label>
                                    <input type="password" id="contrasena" name="contrasena" class="form-control required" value="" placeholder="Contrase&ntilde;a">
                                </div>
                                <br />
                                <!--<button type="button" class="btn btn-link" onclick="recupera();" style="padding-left: 0;">
                                    <i class="fa fa-key"></i>&nbsp;¿Olvid&oacute; su contrase&ntilde;a?
                                </button>-->
                                <button type="submit" class="btn btn-rojo-1 pull-right naran">
                                    <i class="fa fa-sign-in "></i>
                                    Ingresar
                                </button>
                            </form>
                        </div>
                    </div>
                </div>                
            </div>
        </div>




        
        <footer></footer>
        <input type="hidden" name="_peticion" id="_peticion" value="<?php echo $this->peticion; ?>" />
        <input type="hidden" name="_modulo" id="_modulo" value="<?php echo $this->modulo; ?>" />
        <input type="hidden" name="_controlador" id="_controlador" value="<?php echo $this->controlador; ?>" />
        <input type="hidden" name="_accion" id="_accion" value="<?php echo $this->accion; ?>" />

        <div id="_dialogo-1" class="display-none"></div>
        <div id="_dialogo-2" class="display-none"></div>
        <div id="_dialogo-pausa-notificacion" class="display-none"></div>
        <div id="_mensaje-1" class="display-none"></div>
        <div id="_mensaje-2" class="display-none"></div>
        
        <!-- La carga de los scripts debe hacerse al final -->
        <script src="/recursos/jquery_2_2_1/jquery2_2_1.js"></script>
        <script src="/recursos/jquery_ui_1_11_4/jquery-ui.js"></script>
        <script src="/recursos/bootstrap/bootstrap.js" />
        <script src="/recursos/flexigrid/flexigrid.js"></script>
        <script src="/recursos/jquery_form_3_18/ajaxforms.js"></script>
        <script src="/recursos/jquery_validation_1_13_0/dist/jquery.validate.min.js"></script>    
        <script src="/recursos/jquery_validation_1_13_0/dist/localization/messages_es.min.js"></script>   
        <script src="/js/backend/comun.js"></script>
        <script src="/js/backend/ingreso.js"></script>
        <?php echo $this->headScript(); ?>                
    </body>
</html>