<div class="panel panel-default" style="margin: 5px 0;">
  <div class="pnl-heading-rojo-1 clearfix"><h3 class="panel-title pull-left">Tipos de Impuestos</h3></div>
    
    <div class="panel-body">
        <div class="row margin-bottom-3">
            <form id="frmFiltroTipoImpuesto" name="frmFiltroTipoImpuesto">
                
                <div class="col-xs-3">
                    <label for="fdescripcion" class="sr-only">Descripcion</label>
                    <input type="text" name="descripcion" id="fdescripcion" class="form-control input-sm" value="" placeholder="Descripcion"/>
                </div>

                <div class="col-xs-3">
                    <label for="fabreviatura" class="sr-only">Abreviatura</label>
                    <input type="text" name="abreviatura" id="fabreviatura" class="form-control input-sm" value="" placeholder="Abreviatura"/>
                </div>

                <div class="col-xs-2">
                    <label for="fstatus" class="sr-only">Estatus</label>
                    <select id="fstatus" name="fstatus" class="form-control input-sm">
                        <option value="" >- Todos los estatus -</option>
                        <option value="1" selected>Activo</option>
                        <option value="0">Inactivo</option>
                    </select>
                </div>

                <div class="col-xs-4 text-right">
                    <a class="btn btn-sm btn-default" type="button" onclick="filtrar('frmFiltroTipoImpuesto','/tipo-impuesto/grid','/tipo-impuesto/imprimir','/tipo-impuesto/exportar');">
                        <i class="fa fa-search"></i>&nbsp;Filtrar
                    </a>
                    <a class="btn btn-sm btn-default" type="button" onclick="limpiar('frmFiltroTipoImpuesto','/tipo-impuesto/grid');">
                        <i class="fa fa-eraser"></i>&nbsp;Limpiar
                    </a>
                    <a id="btnImprimir" target="_blank" href="/tipo-impuesto/imprimir" class="btn btn-sm btn-default" >
                        <i class="fa fa-search"></i>&nbsp;Imprimir
                    </a>
                    <a id="btnExportar" target="_blank" href="/tipo-impuesto/exportar" class="btn btn-sm btn-default"  >
                        <i class="fa fa-eraser"></i>&nbsp;Exportar
                    </a>        
                </div>
            </form>
        </div>        
    </div> 
      <form id="frmTipoImpuesto" name="frmTipoImpuesto" method="post" action="/tipo-impuesto/guardar" role="form">
        <div class="panel-body">
            <div class="row margin-bottom-3">
                <div class="col-xs-7 sinMargin">
                    <div class="pnl-heading-rojo-1 clearfix"><h3 class="panel-title text-center">Tipos de Impuestos</h3></div>
                    <div id="flexigrid"></div>
                </div>
                
                <div class="col-xs-5 sinPaddingLeft">
                    <div class="panel panel-default" >
                        <div class="pnl-heading-rojo-1 clearfix">
                            <h3 class="panel-title pull-left">Alta / Edición de Tipos de Impuestos</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row margin-bottom-3">
                                <div class="col-xs-12 form-group"> 
                                    <label for="fabreviatura" class="col-xs-4 control-label" style="padding: 0px;"><span class="naranja">*</span>Abreviatura:</label>
                                    <div class="col-xs-8 sinPaddingRight">
                                        <input type="text" id="abreviatura" name="abreviatura" class="form-control input-sm required" value=""  maxlength="100" placeholder="Abreviatura" />
                                    </div>
                                </div>

                                <div class="col-xs-12 form-group"> 
                                    <label for="fdescripcion" class="col-xs-4 control-label" style="padding: 0px;"><span class="naranja">*</span>Descripcion:</label>
                                    <div class="col-xs-8 sinPaddingRight">
                                        <input type="text" id="descripcion" name="descripcion" class="form-control input-sm required" value=""  maxlength="100" placeholder="Descripcion" />
                                    </div>
                                </div>
 
                            <div class="row sinMargin text-center">
                                <div class="col-xs-4 text-center mt40px">
                                    <button type="button" onclick="guardar('frmTipoImpuesto','/tipo-impuesto/grid','/tipo-impuesto/imprimir','/tipo-impuesto/exportar');" class="col-xs-12 btn btn-success marginLat5p <?php echo(($this->puedeAgregar)?"":"hide"); ?>">
                                        <i class="fa fa-floppy-o"></i>&nbsp;Guardar
                                    </button>
                                </div>
                                    
                                <div class="col-xs-4 text-center mt40px"> 
                                    <button type="button" onclick="limpiarfrmTipoImpuesto()" class="col-xs-12 btn btn-primary marginLat5p <?php echo(($this->puedeAgregar)?'':'hide'); ?>">
                                        <i class="fa fa-eraser"></i>&nbsp;Limpiar
                                    </button>
                                </div>

                                <div class="col-xs-4 text-center mt40px">
                                    <a onclick="eliminar('','1');" id="eliminar" class="col-xs-12 btn btn-danger  marginLat5p <?php echo(($this->puedeEliminar)?'':'hide'); ?>">
                                        <i class="fa fa-times"></i>&nbsp;Eliminar
                                    </a>
                                </div>
                                <input type="hidden" name="id" id="id" value="" />
                            </div>
                        </div>
                    </div>
                </div> 
             </div>     
            </div>
        </div>
    </form>
</div>