<?php

/**
 * Usuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Usuario extends BaseUsuario {
	
	public static function ingresar ($correo_electronico) {
		
		try {
			return Doctrine_Core::getTable('Usuario')->findOneByCorreoElectronico($correo_electronico);
		}
		catch(Doctrine_Exception $e){
			return $e->getMessage();
		}
	}
	
	public static function guardarPermisos($permisos, $id, $empresas) {
		
		$con = Doctrine_Manager::getInstance()->connection();
		$cadena = "";
		
		//Permisos
		foreach( $permisos AS $permiso ) {
			$cadena .= (empty($cadena)) ? $permiso : "|".$permiso;
		}
		
		if($id > 0) {
			//Eliminar todas las empresas
			$eliminar_empresas = Doctrine_Query::create()->delete('UsuarioEmpresa')->where("usuario_id = ".$id)->execute();
			
			//Asignación de empresas
			foreach( $empresas AS $id_e => $campo ) {
				
				if( !is_null($campo) ) {
					
					$Modelo = new UsuarioEmpresa();
					$Modelo->usuario_id = $id;
					$Modelo->empresa_id = $campo;
					$Modelo->save();
				}
			}
		}
		
		Doctrine_Query::create()->update('Usuario')->set('permisos', '?', $cadena)->where('id = ?', $id)->execute();
		$regi = My_Comun::obtener("Usuario", "id", $id);
		Bitacora::guardar($id, 'Usuario', 'Permisos de usuario', $regi->nombre);
	}
	
}