
<?php

/**
 * SubsidioEmpleo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Modelo
 * @subpackage SubsidioEmpleo.php
 * @author     Danny Ramirez <danny_ramirez@avansys.com.mx>
 * @version    1
 */
class SubsidioEmpleo extends BaseSubsidioEmpleo {

}