<div class="panel panel-default" style="margin: 5px 0;">
	<div class="pnl-heading-rojo-1 clearfix"><h3 class="panel-title pull-left">Coeficiente de utilidad</h3></div>
	
	<div class="panel-body">
		<div class="row margin-bottom-3">
			<form id="frmFiltroCoeficiente" name="frmFiltroCoeficiente">
				
				<!--<div class="col-xs-3">
					<label for="fempresa_id" class="sr-only">Empresa</label>
					<select data-placeholder="Elige una Empresa" class="chosen-select" tabindex="2" name="empresa_id" id="fempresa_id" ></select>
				</div>
				<div class="col-xs-3">
					<label for="fejercicio_id" class="sr-only">Ejercicio</label>
					<select data-placeholder="Elige un Ejercicio" class="chosen-select" tabindex="2" name="ejercicio_id" id="fejercicio_id" ></select>
				</div>
				
				<div class="col-xs-6 text-right filtros">
					<a class="btn btn-sm btn-default" type="button" onclick="filtrar('frmFiltroCoeficiente', '/coeficiente/grid', '/coeficiente/imprimir', '/coeficiente/exportar');">
						<i class="fa fa-search"></i>&nbsp;Filtrar
					</a>
					<a class="btn btn-sm btn-default" type="button" onclick="limpiar('frmFiltroCoeficiente','/coeficiente/grid');">
						<i class="fa fa-eraser"></i>&nbsp;Limpiar
					</a>
					<!--
					<a id="btnImprimir" target="_blank" href="/coeficiente/imprimir" class="btn btn-sm btn-default" >
						<i class="fa fa-search"></i>&nbsp;Imprimir
					</a>
					<a id="btnExportar" target="_blank" href="/coeficiente/exportar" class="btn btn-sm btn-default"  >
						<i class="fa fa-eraser"></i>&nbsp;Exportar
					</a>
				</div>-->
			</form>
		</div>
	</div>
	
	<form id="frmCoeficiente" name="frmCoeficiente" method="post" action="/coeficiente/guardar" role="form">
		<div class="panel-body">
			<div class="row margin-bottom-3">
				<div class="col-xs-7 sinMargin">
					<div class="pnl-heading-rojo-1 clearfix"><h3 class="panel-title text-center">Coeficientes</h3></div>
					<div id="flexigrid"></div>
				</div>
				
				<div class="col-xs-5 sinPaddingLeft">
					<div class="panel panel-default" >
						<div class="pnl-heading-rojo-1 clearfix">
							<h3 class="panel-title pull-left">Alta / Edición de coeficientes</h3>
						</div>
						<div class="panel-body">
							<div class="row margin-bottom-3">
								<div class="col-xs-12 form-group"> 
									<label for="id_empresa" class="col-xs-4 control-label" style="padding: 0px;"><span class="naranja">*</span>Empresa:</label>
									<div class="col-xs-8 sinPaddingRight">
										<select name='id_empresa' id='id_empresa' class='form-control input-sm'>
											<option>Seleccione Empresa</option>
										</select>
									</div>
								</div>
								
								<div class="col-xs-12 form-group"> 
									<label for="id_ejercicio" class="col-xs-4 control-label" style="padding: 0px;"><span class="naranja">*</span>Ejercicio:</label>
									<div class="col-xs-8 sinPaddingRight">
										<select name='id_ejercicio' id='id_ejercicio' class='form-control input-sm'>
											<option>Seleccione Ejercicio</option>
										</select>
									</div>
								</div>
								
								<div class="col-xs-12 form-group"> 
									<label for="id_periodo_inicio" class="col-xs-4 control-label" style="padding: 0px;"><span class="naranja">*</span>Periodo de inicio:</label>
									<div class="col-xs-8 sinPaddingRight">
										<select name='id_periodo_inicio' id='id_periodo_inicio' class='form-control input-sm'>
											<option>Seleccione periodo de inicio</option>
											<option value="1">Enero</option>
											<option value="2">Febrero</option>
											<option value="3">Marzo</option>
											<option value="4">Abril</option>
											<option value="5">Mayo</option>
											<option value="6">Junio</option>
											<option value="7">Julio</option>
											<option value="8">Agosto</option>
											<option value="9">Septiembre</option>
											<option value="10">Octubre</option>
											<option value="11">Noviembre</option>
											<option value="12">Diciembre</option>
										</select>
									</div>
								</div>
								
								<div class="col-xs-12 form-group"> 
									<label for="id_periodo_fin" class="col-xs-4 control-label" style="padding: 0px;"><span class="naranja">*</span>Periodo de fin:</label>
									<div class="col-xs-8 sinPaddingRight">
										<select name='id_periodo_fin' id='id_periodo_fin' class='form-control input-sm'>
											<option>Seleccione periodo de inicio</option>
											<option value="1">Enero</option>
											<option value="2">Febrero</option>
											<option value="3">Marzo</option>
											<option value="4">Abril</option>
											<option value="5">Mayo</option>
											<option value="6">Junio</option>
											<option value="7">Julio</option>
											<option value="8">Agosto</option>
											<option value="9">Septiembre</option>
											<option value="10">Octubre</option>
											<option value="11">Noviembre</option>
											<option value="12">Diciembre</option>
										</select>
									</div>
								</div>
								
								<div class="col-xs-12 form-group"> 
									<label for="coeficiente_utilidad" class="col-xs-4 control-label" style="padding: 0px;"><span class="naranja">*</span>Coeficiente de utilidad:</label>
									<div class="col-xs-8 sinPaddingRight">
										<input type="text" id="coeficiente_utilidad" name="coeficiente_utilidad" class="form-control input-sm required" value=""  maxlength="30" placeholder="Coeficiente de utilidad" />
									</div>
								</div>
								
								<div class="row sinMargin text-center">
									<div class="col-xs-4 text-center mt40px">
										<button type="button" onclick="guardar('frmCoeficiente','/coeficiente/grid','/coeficiente/imprimir','/coeficiente/exportar');" class="col-xs-12 btn btn-success marginLat5p <?php echo(($this->puedeAgregar) ? "" : "hide"); ?>">
											<i class="fa fa-floppy-o"></i>&nbsp;Guardar
										</button>
									</div>
										
									<div class="col-xs-4 text-center mt40px"> 
										<button type="button" onclick="limpiarfrmCoeficiente()" class="col-xs-12 btn btn-primary marginLat5p <?php echo(($this->puedeAgregar)?'':'hide'); ?>">
											<i class="fa fa-eraser"></i>&nbsp;Limpiar
										</button>
									</div>
									
									<div class="col-xs-4 text-center mt40px">
										<a onclick="eliminar('', '1');" id="eliminar" class="col-xs-12 btn btn-danger  marginLat5p <?php echo(($this->puedeEliminar)?'':'hide'); ?>">
											<i class="fa fa-times"></i>&nbsp;Eliminar
										</a>
									</div>
									<input type="hidden" name="id" id="id" value="" />
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>