<?php

/**
 * Bitacora
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Bitacora extends BaseBitacora{

	public static function guardar($idTabla, $modelo, $accion, $referencia){

		try{

			$oBitacora = new Bitacora();

			$oBitacora->tabla_id = $idTabla;
			$oBitacora->usuario_id = Zend_Auth::getInstance()->getIdentity()->id;
			$oBitacora->modelo = $modelo;
			$oBitacora->accion = $accion;
			$oBitacora->referencia = $referencia;
			
			$oBitacora->save();
		}catch(Exception $e){

			//echo $e; exit;
			// nada
		}	
	}

	public static function grid($usuarioId, $modelo, $accion, $referencia, $desde, $hasta){

		$consulta = "
            select
                usuario.nombre 	as usuario
                ,bitacora.modelo as modelo
                ,bitacora.accion 	as accion
                ,bitacora.referencia 	as referencia
                ,bitacora.tabla_id 	as tabla_id
                ,bitacora.created_at 	as fecha
            from
                bitacora
                inner join usuario
                	on bitacora.usuario_id = usuario.id
            where
                1 = 1
        ";

        if($usuarioId != "")
            $consulta .= " and usuario.id = ".$usuarioId;

        if($modelo != "")
            $consulta .= " and bitacora.modelo like '%".$modelo."%'";

        if($accion != "")
            $consulta .= " and bitacora.accion like '%".$accion."%'";

        if($referencia != "")
            $consulta .= " and bitacora.referencia like '%".$referencia."%'";

        if($desde != ""){

            $desde = str_replace(array("'", "\""), array("´", "´"), $desde);
            $consulta .= " and bitacora.created_at >= '".$desde." 00:00:00'";
        }
        
        if($hasta != ""){

            $hasta = str_replace(array("'", "\""), array("´", "´"), $hasta);
            $consulta .= " and bitacora.created_at <= '".$hasta." 23:59:59'";
        }

        return My_Comun::registrosGridQuery($consulta);
	}

	public static function usuarios($seleccionado){

        $consulta = "
			select
				u.id 		as id
				,u.nombre 	as nombre
			from
				usuario u
			where
				u.id in
					(select distinct
						b.usuario_id
					from
						bitacora b)
			order by
				u.nombre
		";

		$query= My_Comun::crearQuery(null, $consulta);
		$opciones .='<option value="">- Todos los Usuarios -</option>';
		foreach($query as $item){

			if($seleccionado==$item["id"]){
				$opciones .='<option value="'.$item["id"].'" selected="selected">'.$item["nombre"].'</option>';
			}else{
				$opciones .='<option value="'.$item["id"].'">'.$item["nombre"].'</option>';
			}
		
		}
        return $opciones;
	}

	public static function modelos($seleccionado){

		$consulta = "
			select distinct
				b.modelo 	as id
				,b.modelo 	as nombre
			from
				bitacora b
			order by
				b.modelo
		";
        $query= My_Comun::crearQuery(null, $consulta);

		$opciones .='<option value="">- Todos los Modelos -</option>';
		foreach($query as $item){
			if($seleccionado==$item["id"]){
				$opciones .='<option value="'.$item["id"].'" selected="selected">'.$item["nombre"].'</option>';
			}else{
				$opciones .='<option value="'.$item["id"].'">'.$item["nombre"].'</option>';
			}
		
		}
        return $opciones;
	}

	public static function acciones($seleccionado){

		$consulta = "
			select distinct
				b.accion 	as id
				,b.accion 	as accion
			from
				bitacora b
			order by
				b.accion
		";

		$query= My_Comun::crearQuery(null, $consulta);
		$opciones .='<option value="">- Todas las Acciones -</option>';
		foreach($query as $item){
			if($seleccionado==$item["id"]){
				$opciones .='<option value="'.$item["id"].'" selected="selected">'.$item["nombre"].'</option>';
			}else{
				$opciones .='<option value="'.$item["id"].'">'.$item["nombre"].'</option>';
			}
		
		} 
        return $opciones;
	}
}